# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
  - R_CODECOV_TEST=true
  - R_CODECOV_EXAMPLE=true
  - R_CODECOV_VIGNETTE=true

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-mgcv r-cran-matrix r-cran-deldir r-cran-abind r-cran-tensor r-cran-polyclip
  - ./run.sh install_aptget r-cran-sm r-cran-maptools r-cran-spatial r-cran-tkrplot 
  - ./run.sh install_aptget libgsl0-dev libfftw3-dev
  - ./run.sh install_r spatstat.utils goftest gsl locfit RandomFields RandomFieldsUtils fftwtools

script:
  - cd ../..
  - rm -rf spatstat/spatstat
  - git clone --depth=50 --branch=master https://github.com/spatstat/spatstat.git spatstat/spatstat
  - cd spatstat/spatstat
  - if [[ "${R_CODECOV_TEST}" ]]; then R -e 'covr::codecov(type = "test", quiet = FALSE)'; fi
  - if [[ "${R_CODECOV_EXAMPLE}" ]]; then R -e 'covr::codecov(type = "example", quiet = FALSE)'; fi
  - if [[ "${R_CODECOV_VIGNETTE}" ]]; then R -e 'covr::codecov(type = "vignette", quiet = FALSE)'; fi

notifications:
  email:
    on_success: change
    on_failure: change

