language: r
sudo: required
warnings_are_errors: true

apt_packages:
  - libgsl0-dev
  - bwidget

r_binary_packages:
  - mgcv
  - deldir
  - abind
  - tensor
  - Matrix
  - maptools
  - tkrplot
  - spatial

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
