language: r
r:
  - release
  - devel
sudo: false 
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install anysize; fi

addons:
  apt:
    packages:
      - libgsl0-dev
brew_packages:
  - gsl

r_github_packages: 
  - baddstats/polyclip
  - jimhester/covr
  - yihui/knitr

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then R CMD INSTALL $PKG_TARBALL; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type = "vignette", quiet = FALSE)'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type = "test", quiet = FALSE)'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type = "example", quiet = FALSE)'; fi

env:
  - _R_CHECK_FORCE_SUGGESTS_=false
